name: GCP CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  DASHBOARD_IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/airbnb-app-repo-prod/dashboard:latest
  PIPELINE_IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/airbnb-ml-models-prod/pipeline:latest

jobs:
  build_and_deploy_dashboard:
    name: 'Build and Deploy Dashboard to Cloud Run'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
          workload_identity_provider: 'projects/605975162766/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: '605975162766-compute@developer.gserviceaccount.com'
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Configure Docker for Artifact Registry'
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: 'Build and Push Docker Images'
        run: |
          # Build and push Dashboard
          docker build -t $DASHBOARD_IMAGE -f dashboard/Dockerfile .
          docker push $DASHBOARD_IMAGE
          
          # Build and push Pipeline
          docker build -t $PIPELINE_IMAGE -f pipeline.Dockerfile .
          docker push $PIPELINE_IMAGE

      - name: 'Deploy to Cloud Run and Update Jobs'
        run: |
          gcloud run deploy airbnb-dashboard-prod --image $DASHBOARD_IMAGE --region $REGION --allow-unauthenticated --quiet
          gcloud run jobs update airbnb-data-pipeline-prod --image $PIPELINE_IMAGE --command "python,main.py,run-pipeline-all" --region $REGION --quiet
          gcloud run jobs update airbnb-ml-pipeline-prod --image $PIPELINE_IMAGE --command "python,main.py,run-ml" --region $REGION --quiet
